language: python

python:
- '2.7'

branches:
  only:
  - master

env:
  global:
  - DATABASE_NAME=database_name
  - TEST_DATABASE_NAME=test_database_name
  - DATABASE_PASSWORD=database_password
  - DATABASE_USER=database_user
  - DATABASE_HOST=localhost
  - DATABASE_PORT=5432
  - DJANGO_SETTINGS_MODULE=qmsg.settingstravis
  # Browserstack BROWSERSTACK_AUTH BROWSERSTACK_KEY
  - secure: WFMDDyr928betQVbZWwf3VKcNnG3N6kaxeAd9MSMM9SsNoPo+6a+83/7TSC4dLLToBJs5onVmdD0C6W0hpUHi1eo81gw+RCxJS7ZQ3MGJ+cibONkotUmgLY0e9RZX7Kj9b+jXRHxlEEJEo6UmXVlOnTgiYtwGFjJ+ZZ2Gfa8mQF30DLsDOm18p8qXzzuKeid0HhwGx38RJeoZpDfs14Aop0eBLw5B8MRtbm1cnsdDfQOVpN7G5gWrGqC5/E8o9bgt2jMqBes3+tcEOfBGHEPDrm6KO455Qtellcv8qv4UwBCGUkv3SzU48HphXyhM1PLhMcmpoQv1Xdzd1KWiOjS2qS9omaDwbav5uaJ4ZpKBJEytic6Zeia/Kuw+gXXCkqDJVxt9ciumCxqFvPEGcwdT/WjmmSZUPq7blunzkdhF/xh40AcKKS0/VzTzNdR3tVrX19Mo7lDj/q1zQA9L0y5DNFxi51TM+ZV2hPV1wwUEi5Y4flgveoPOSKIAB7SyxNcukHob7inx9kAizNHXjsOkBmtKb1LYNxHMvdqsyo2lX24PFaGny/9o1UIpK+eYZLlp38jnLKTRrRqoCRFwSdaI5cCJ3djPMN0c8+lvXRDkDhDaaCp1SijP/6Zwaqf8KWrvC6RrV9/vahbIb6frY6XtiFxJX3xgSO4etqs43yWZBs=
  - secure: IjJys+qPY3CQVoWY2oaqqMfMaoQ9orPF7ZY4Gm7M9KBpwhoIEClOuHkDY3FBr+X8xY7OI/D3Y2/e0iro2QQ6CodM8JJToC1Zm69miXBjX3SxhCmWkvQVE9vDCzmr0JRX/9yX9sHI92RV7YaSkIJ6qWNGd7vvf1ZvhQj2eAXxtsrjnMwyagiwjyU0f/9i0O8Whvn5AywTcwoO6lgK0V2Z7+BjSquyHFxbNcY72B2OGT4fVBTv607DH4wehUNgVrQPnu+PIHXPG1srSSn2zF8C2pjo+sslW6jywNDhyoFZ8V58TKvW0CX6WA1VgsJp7Gxt+O/OtNkdDrdqNm2jwZ06SGsfgZqYPQB/prjZoip8JQvYvlMH3r7htz4+VHuseuwX2XQuxB7CkxWZz3c4WXqfGsPYMlb6MYeyIZSegy7hkoKf/d5u5B1K2BGYt3RRd2OdgeFE3YGORtzH/ebNZyU4/QvAu5X1W0M5/j/zSgn3PZ4kGfYxk2Z5RB4Q8MEh7Ns2wkr+VJFjcZuWpkGY3eOKSQvKoOwR3lzVxwGqOGSs3vJmOD1JijtyaEn854UU4zHsiKiqW3PFYX+nm+zEwyCirPaNy7tgqELOE+hhz+IhKY+4x+tl0EzgPI0QM7KIbOpDYkUJTqS0WuIUUaDp+kHVKKJTLCJehwg0/37VxvCV4aI=
  # Codeclimate CODECLIMATE_REPO_TOKEN
  - secure: Kc6JeqIYToQAfBGDFm1xpFxt1f7JdQwsz7ciBK21cPW4GekGyK+yDYcSv/Q9ApaZ/igOW8v3b6sKui9xZyWnzuNiw4/iKOvJy74cg1ypy0LqRYT+PnFIpGungOnHp3Uy5p2PqK2AEZINQVX1NVDB8hvc7g+2Stlq/+ldziSMrS1zkq2pYae61k6IGkp3JFw3hmDRdbw6FAFyCFIgJ2MlFEruK/yv2CRLkZBZyQkxCFFVc7abALKDUQevogA3s08o2q7VtiXIQjluc3p9X4z8UHcP2qgbBh+mWcshus1WHWzfFvPqFzVJJVx/2KsO0kd57ob9JLkTU5xzTvc/+LcHLIWbZMI6eHnjM4Z2AwRpktwAeY+C1U/nDe3MwOwHwmz81yzRqIjnpN5M7hhLf83Wzni3daouC999NHmccKligKW4iX7Fmr3Uq2yXZrzZtRdrxQpfi0WvxJNEQPLGIYmGDcRlKngHdlvqYapVRQBG8+vHiwYMdNyQRmug/nrhwHC5HsRVm0VtfLkodRR4z/Fcp6hLBG5GJ7J08GRxrutLvgztYdmL6KwN6YSaebu+FSSjRCFR1L/hKTGLNzj6/dHuO0Bc38WsZvI6aCqwylw1a0eTHkp87sI/MpkxIvEULB6hXAgEYgu0ToHleDgknnb9cByvS5e32gc2UKpA6jOF88o=
  # Coveralls COVERALLS_REPO_TOKEN
  - secure: IGToGc86G8wkRcGFe5ZINPMBBYPbCeZsrvayA657mKAMHaHEM+sh0O43dOemqagGvZtJOUY0sLTlTxh20JkgWTHmX+abyzOvniMBuqkNcBC3eZxHCnRQBjLm6WT12lWrdXreBeEdkiLRh5QFkynSUf1drd0ViynXzUeyi9KJPhjJVrjph/o3O6LcD4zdWvFKlFZQ6REEMW0kIbGYBxnVI4hbkYQu88xs+bm0MMcKJB2dkTWUiPKjn3dH2c44NAkXHuDUma+qbD48ZiSnYTIttBNxKM8pASYB5YoI1Dg9Ol0VxeOutbf5RvFlS+gPN02+p/UHTB2vhTJJz50FzOrys4iBEKSY71hCBFUS43I+sk2jFTLb5O1bRyiMEESBezRJKxggRs405G3hxSDPzawzkNjJOO3KJkv7duo9kzWE2QnBqdEs0pNNopRGtxvblKu4EFVANc8DJcAmhElvEbr5UOaOOi+evcVSTYg8xbpM3tACzw3WYyVO134jU+ut7RWYkDs9PEwmvXjNs4xTgpas8FFSBSFhQ6SMTt3K5yy1xDvisyiLphpYJGANVJoE75LnDCllzodIc1lPvVBBMXHwpCEg4OuETMfAMIhrx2VoT+w0YRuUjBzyNtw0yp2QhrbWc6CbZe+0ci8T7fLFvjxgbPeCr00/s07ftSrq7Q+XSME=
  - RADONFILESENCODING=UTF-8

install:
- pip install -r requirements.txt

before_script:
- "./scripts/create_database.sh"
- python manage.py migrate
- python manage.py runserver > /dev/null 2>&1 &
- "./drivers/BrowserStackLocal --key $BROWSERSTACK_KEY > /dev/null 2>&1 &"

script:
- pep8 --exclude=migrations apirestv1/
- pyflakes apirestv1/
- radon cc apirestv1/ --min A --exclude "apirestv1/migrations/*" --show-complexity
- coverage run --source=apirestv1 --omit=test* manage.py test

after_success:
- coveralls
- codeclimate-test-reporter

deploy:
  provider: heroku
  api_key:
    secure: YXaqhcdbBA1uVTq6Zgz/at0gn/gTrdTcnfkw7JQfjo8yH5U61l4jpJ//X5KUegyA8JOgcosw9cz42/CuQSKRb4w80vO/fGqQbmvXbzPobc8uLXJPxAXiBzVuNyZyEn3Z37gFGkAKT2FvDGxaXKdMDNsXgRdOEN1U1I3VP9RJeNoXK1LTToKgpr3XlpoJ0HiUKIjahBWPbI//B2n/DZwb7h7uBD0rdlC9i9G3iw77SZQVlwd8vfaElECzI2H8WDjGbNA4sRnfRbwyjRSPCX5uXDV2VCO0MZiC0OE/gOhWpLWCoFWzX2nuLlj6wnWLNyIk9CB3/t9IqC/yVCB5nroD+XS460gJdqN1S87rnFXnTXblhNMKr+ppmyOyhiqqilIRMteT0DMhVK8BK1MjB4y1rq1whgpkoG9n4qPcIlxAxT0sBjtPvg68+bVbc8/kK2z3ppxNhIy8bt0DPByrBw3d5v412ppG/+B7B1uC3zgVDUZEWB/D5GodZbXux83Z2u0MFNlH8kJiPCOLbj1OvikGJnXdcuddyHWvz8gt6isNv1i8LHWnPlpPp0IbNX+6pOhyMN7Zvi1rPd2St57ZQqLzcPqAbku22GwIptPEnv2xDpLmMVPo5B0q3qt6gCdJv2xE4ywYjd0I/6aBGubCBSKg/aB5HhhBmt6U+nBraM5/AYw=
  app: qmsg
  strategy: git
  buildpack: heroku/python
  run:
  - python manage.py migrate

notifications:
  slack:
    secure: X8Qeqnh4hKXLMaY3DOABNYymXVVRSHRyeVWPwJJ1YPz7qyocpz7THK81kNJDjnchsOT8sfHmkgPMcZ+gQ85IezYxiXak/vs3El4I6P95s5bSkxUcxJN1rYyF527sanAPEVMPCXWu00JQeJNlSkE5WRpbRpBBQ+CAtG4KxQV39enbT720p6IS9w03yEwNfa80iMQhJkCMdMjXKO1FN3fRieVZ3G0xw76O6KpImFtVdrN3jKwvYrjVfTcqDOint26Xn7VIfJgGHG1TQWgUDuZgksniYHLxlwWP0rYE94FmyXId1vizvQmOw6d7xDrKtcGxg2EwcKGr8/iAvdCN+55oKGg47TFqIy6nBsDnv2DkOj/07migSvqHQb453knI1L9jun6jCAjC3dJpNGxL6bN44IFAFuwasas06jkVEjwyqS/LEk9BtKlJSHwHdTIqYOTnJDhF/a4Qp0s2aLYQ+xu7oaO4FsvaWiwEh5nOoJ8w8Qlo5mlY1b4fyh7skG+8gv76B25WsNUoQyReFbGrlA5GgZW+1Xd5c+aWm/SUBFRsjedkw/0ctrWqoYxwJqKFV/BAla9GhtK+HeLcbo99pFO+UWNu1BVmWg5u964H20fg2wA/z9pavzruNU8Ha0FeLLx8aS3tstl8Pdi5E0VUb9jjUZRheAgtsgZZRICBg90KP7A=
