language: python

python:
- '2.7'

branches:
  only:
  - master

env:
  global:
  - DATABASE_NAME=database_name
  - TEST_DATABASE_NAME=test_database_name
  - DATABASE_PASSWORD=database_password
  - DATABASE_USER=database_user
  - DATABASE_HOST=localhost
  - DATABASE_PORT=5432
  - DJANGO_SETTINGS_MODULE=qmsg.settingstravis
  # Browserstack
  - secure: AhyYvOZz8LU7+h0BMRPokhV1hz5LLfTV6xJ6fe5Qk4dOrerpu2ZThvgUHdbjPFl1DQoxU1wqKTfOmX+lnlDrOLQOvQQdrZdc8gFpl42OY8AzbNC/90R3WjYGXBYXyEHCBYoZxUY8ydsZg9BCYpsAOZVDHfAIM6FY2P6x24+M/DR/RSYnhOZj4HEjdGu830bBOfeX+SMouuuGY1NBhTaKCY860wf+5WDLH5OWUqf1yo7KOZCuwfPJrH7mASz8RWtu/8rNI1cWB/cYOlsD7P/mnGfNvKoLEWPYUyLR1HuIID0WeEvpu0J0E3TSh7+cJ4eiqB8NSDt64DtB4dUL225CzKi02euHD0RuNvLNaVUMf6PF7OD8oUYhHPiulfoKWLvV6w0M9CsZpT9PGjd4ym7tij5zqPMvXhYowDsLVQ0njmVFx0vtp9mtqQU6R3pH4VLGcbGn38DPhqwIMPOFkT+ndS2qoXBA33/WVauopw/A7t6fzz4kvya3xnsHvonDypLz1Z6Yy8yrAuJ0f60O3QpBljOVVzz6I2VNw+a692aooiGrzV7FRlHeX5PJVFj56hZubVKUABwXG5nC2sMeqPW9evdLPWQqzMObdrqvvvfunbp/KHDcE34IpIX1uUHiU6ojDfZGzQCtVy6o9fmBS4JoyoaJkSD9YyJ9WgV2W1nrVY0=
  - secure: J30pUzZ0MmsrG3UCTtpMSjwG5+Tvb7vgdGzKmHzJTSLDrwTQNxe7AIkJshAHtIl9sN1/7dYdwHg+/m9AaIGcXHx1FJ43neLkCwmJaN/m/17yLMdCTbNzPrx2G5WMUWDNfOEH35m5Y9uEL1PpichAcXdP3UX+fDUFjnFjh00HqQJ3Lv5XxFNI4DZqn3brVQnL+8dPvw743sEKTSyQGFKDBL9lMqJwrAbm8AMjabHfxvT1wOnNYu4wNqqXZscvzx2cB/4EAMm/M96nGYndVKbctI1EaUqpGBm0CakRLbEI1ogo5yU8vFzqkMY2QM3JkdhE2dqPbhP5iW30NrgWIqJODb44ajgrovjEy/NPnr+57NpxHNrRfr/zlsnhZtFCQWMJlBKIFOLOIS4kQfzjdbN9U6Jkog70HVoJpn22JT02+RYKqlHpkAwfOnUKcGKSTgH4QKN/a0ROTLEZrASqlu7sKupqpAgMOXKRORv7BOgD5aoWidbuyXlT6aXwEx7hFUXDYBu0PdQpmnQ7XNOjyAi0l4fhQK7ndAqLHrmRvT3Cbwj5MNeDyiwe3b/xZMQt1Rz1/ViOIka1OjoAhFZ/mvbLit3s7BPHdwmSu/D+IqwUzPW/ntEIgRe8dUacWlSa71mkxJ6YflCETJYZFqoWFNtbEX3CemzlAxTjjVXgajTIZZA=
  # Code climate
  - secure: lcdGAnyFRsWAFnZgFtmjO7SNMctcVHdfGABR21RVkxOF0OXHRxowf4KUOBqVTZNNqckzk5XCH3BWca3yeRpqjVHDeKVT1Z5IkQL2dZdcnXkvxUW31SdjEUCnMG9SgbfZP2U/0P0Aw/bToZW6S2zPQYw4jbXow0s0uaTZx7NzAO76QwOSYvH8yqyVLuF0MoCXpIYDIKUioZ8jCq6OfyMbSC2+9IHSjWjMWLcfbAltf089WA8fVSBJfpbZqxApQ3R0xtOUr8fgp4tzW1NRXBpy87WwSgoB9RFaErXsSjuxVTXHiLcEfMjEabyFX8j9II70EDn+c634WgJPhiXpQ+UDzoHZXqsgYnxGXMYQeA9kBQcG5ZM1VCFx/EfJOquaUz5m8VXrzbLvPejOhE/GebATZMOafVKeOu6srzSGele21iC1hvgvg5y1mFms6VUkmfcXkG28xG0l61xozzyAqWquXikaqmGjV+ceZ0L04Dy0bwXS0VCKOCzWoDKXPC5SGujlm1nqm1jpXxX87nVX7i7XVx4/zVreQ/dCD0R6JWDTTmsfI/rqr19hbRkw22RZ959ogvAlf0dquOcOEU3aSn1pYhDRYvGNVkkHVTmVsURskVIusY1FEcRg2CrPmFnapGpTkVlsG/YM9HkZ1hoLoF08XMOIkcCsOiT1my9eR1AGZ9o=
  - secure: NenhcN/mPRvKt3F6Sg/xfgdGEjp8mUq75G/dUI1D0ivCUhEZARAxuAIgtJXyGMIoCPhdxJQRRszsXWouMG8pRaL1Xyw0ImJIPV7ufFiPNTvWCQQT5h3nt5hb/fBzekiDJpNtTvQvROd4vJwNIdhgfp+er1G2+L4a3WyiH8EHkopTlF4HHI+3JKrOM+OWVQICZW4jDALeIZUHBXMCGH2Ng4QGCMBYuDcHJ43mJKDOmKBsRMB4Biy6aVAAbL6lfHRaw6zG7jNLttGKiANkZjXOW5WS2ueSHYpd5SIMU2RMXgBX/H+eVlPuVCqM92vkmSSquw3V8NCpEOHXlkCBfjH4gkWwggWyr6vM2sSglH206raVJ91yyk08lh+YIapBoUYWQtFgpsJWMaXOcEel43vcxO4eW3z6KgcY7WhDLMgYeA45N/cmwf/zXJQFNdFL/ww+wjoBTWLEH+wD6/kSFdKY7ONBsuSteLjdJRJRgN+q8rma6y+xEoZ7hH4/H+nStU6y4oKvhy/uS6NMWUOSpvxqKD3Tyma0gQLgXJs4pDaWxjdt4RXNA4bxyEujfrkbXAxX7GKS96rzjbfywwzMBrto2/Er3ODu/TflOn0eQXGlDYRhXrCoJ3dzgtL4lZ1dDH6RAVV9hlznRRTrdYk1pFZxwLNumGCvYxIKpIpZl1b1n7U=
  - RADONFILESENCODING=UTF-8

install:
- pip install -r requirements.txt
- pip install codeclimate-test-reporter

before_script:
- "./scripts/create_database.sh"
- python manage.py migrate
- python manage.py runserver > /dev/null 2>&1 &
- "./drivers/BrowserStackLocal --key $BROWSERSTACK_KEY > /dev/null 2>&1 &"

script:
- pep8 --exclude=migrations apirestv1/
- pyflakes apirestv1/
#- radon mi apirestv1/ --exclude "apirestv1/migrations/*"
- radon cc apirestv1/ --min A --exclude "apirestv1/migrations/*" --show-complexity
- coverage run --source=apirestv1 manage.py test

after_success:
- coveralls
- codeclimate-test-reporter

deploy:
  provider: heroku
  api_key:
    secure: kMlzaQnQ7Do0m8wg7hDY7Ke57e8wGw0v9PtrA3tQz9d8+3YWMLaNN2m6Aou/THm0Ypgv3bllWTjqDPqIa0UT3P9/iY07Ps2XbtvrnKCQtTDVl+Oyt/8pMYAoKZUu3l1u1Aq5htfjg0r823dHHbk8oifo/mOX5qFfJaK5uh+z9lcIaSfwKFXeDlqHVbwdYY28pxlM4fU0VZ7HYfYXMKDihscLaqoAHutcz7e7aAcCZBqPFfUk9QlP8IQPcuejYcOVBV59J4inic5IRQR6NWrDc/sxzf13+29AT9inAvv4EZultZQ9cYtZz6gIGon2FqBXyFKjZBByk7FxJDK64TNdybn04Pb7lydMf/fkuvW1ZNE3Fj+Tql13rwpwyecpQaCTkWswXSLNtzvXaPfcbe4lz3X730LLFyXZeI14BpEOE2kdNuhfgCU2UnQml4iQ1KxkcTi7eFRdtsz55sQQznOLQlFyJL3200P80fnT4EmU/PGe3mT/8gVDvFpZDWbVuZV1USU0qwULvWEhpjV9YbEUgm95E1bx9XZ69nh+iIkJwKJvlon2txRqYQe+WI+8VIg5BmKm7zuzOj8ME/iMgiqPPUD9SxwJ5A7lW8Kfeen/l/IUm57IewsrZGaVLLZLNbwDWv00zaibaq9HWJtHAbmh9N5gCPnp8u7sblWSzkeNHNU=
  app: qmsg
  strategy: git
  buildpack: heroku/python
  run:
  - python manage.py migrate

notifications:
  slack:
    secure: Xf7iiHjy4P5GUCN9nYbDcbTuiQ6a2oX3mGhIqe7xym9pDj6KaA71xP6HfENG8wcIEIDxZA5ZU+/bzEx9PPJcIMF/Oe4ub+HjR3c6e89c/ztCVR42HuwUAQPor91F2SYfszJ3CQmpUdR2AXa7pk1vmWd37hLJ4njnMGaMyoInB+pSU89TtYgj7uxUUv6ic2njsHquCaDt3VNGXgRSa1dR3gkON15s/mdjWsONTxsZ0+66t8e17rKimlKdc+ZNlyd++bHXuvjBninmN7ERORtV9sPCMzmLn0Slml9kZONeQU4Kupi5F9BJEbe4mmlE+lTXcMBPwgZ/eCBQbQil3iJUZFN/p7Zl6UB5uF1dFAgIj/61HUaAW03mOqHLPan3KPH1rMl2np/hA8wEddowkkN9Kq0NuUUPDSO7G31Al3+shoK6Kq7AoCwCl+/1asWtNCStu0Q7Mq+axGVnmjXwfSzBE7J0PynKfWiBv1mNNOAJxwTKBEXeZr4tp+idSEnpiNYwDkigGhoUSVP07IH/jJmD67FBScgGr+eM8m+1PYzdyeINZj/Fu3LdKioQtVtPE7vmv2JUKchwFKaXFosEzucAeGVwff7fqChwOwPUYCjv+xpD9lNGESbHV2NyL/h8s0nl1+gg9g4LunuvwthHymGAI6c8t72wrjYDlcSfgVQWOBc=
