version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "80:80"
    volumes:
      - ./src:/src
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: dg01
    command: bash -c "python manage.py makemigrations --settings=qmsg.settingsdocker && python manage.py migrate   --settings=qmsg.settingsdocker && gunicorn qmsg.wsgidocker -b 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - ./src:/src
    expose:
      - "8000"

  db:
    image: postgres:latest
    container_name: ps01
    environment:
      POSTGRES_PASSWORD: password
